### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'semantic_release.commit_parser.token.ParseError object' has no attribute 'descriptions'

### ISSUE THREAD

**Issue by niccokunzmann** [python-semantic-release/python-semantic-release#1019]
### Description

I am getting this error after updating (from 9.8.1 to 9.8.8):

```
jinja2.exceptions.UndefinedError: 'semantic_release.commit_parser.token.ParseError object' has no attribute 'descriptions'
```

### Expected behavior

I think, I would like to see it without error...

### Actual behavior

I see the error.

### Environment

https://github.com/mergecal/python-mergecal/blob/ce7b73c50785a9d3ac8fca8a627420e58ad389ac/.github/workflows/ci.yml#L92

-  **Semantic-release version:** GitHub Action 9.8.8 

<details>
<summary><code>git log --oneline --decorate --graph --all -n 50</code></summary>

```log
*   ce7b73c (HEAD -> main, origin/main, origin/HEAD) Merge pull request #8 from mergecal/renovate/typer-0.x
|\  
| * 634b106 fix(deps): update dependency typer to ^0.12.0
|/  
*   4359654 Merge pull request #6 from mergecal/working-merger
|\  
| * 1ce87e7 feat(core): implement calendar merging functionality
* |   7cf1c7f Merge pull request #4 from mergecal/renovate/wagoid-commitlint-github-action-6.x
|\ \  
| * | 3b5dac3 chore(deps): update wagoid/commitlint-github-action action to v6.1.2
|/ /  
* |   5f57d94 Merge pull request #3 from mergecal/renovate/python-semantic-release-python-semantic-release-9.x
|\ \  
| |/  
|/|   
| * 6dee817 chore(deps): update python-semantic-release/python-semantic-release action to v9.8.8
|/  
* 629fb86 docs: fix codedev link in readme
* 9a5b6f2 (tag: v0.1.0) 0.1.0
* 989334a feat(merge): implement calendar merging functionality
* fd12c9e feat: initial project setup
```

</details>

### Configuration

<details>
<summary>Semantic Release Configuration</summary>

```toml
[tool.semantic_release]
version_toml = ["pyproject.toml:tool.poetry.version"]
version_variables = [
    "src/mergecal/__init__.py:__version__",
    "docs/conf.py:release",
]
build_command = "pip install poetry && poetry build"

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    "chore*",
    "ci*",
]

[tool.semantic_release.changelog.environment]
keep_trailing_newline = true

[tool.semantic_release.branches.main]
match = "main"

[tool.semantic_release.branches.noop]
match = "(?!main$)"
prerelease = true
```

</details>

<details>
<summary>GitHub Actions Job Definition</summary>

```yaml
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  # ...

  release:
    needs:
      - test
      - lint
      - commitlint

    runs-on: ubuntu-latest
    environment: release
    concurrency: release
    permissions:
      id-token: write
      attestations: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      # Do a dry run of PSR
      - name: Test release
        uses: python-semantic-release/python-semantic-release@v9.8.8
        if: github.ref_name != 'main'
        with:
          root_options: --noop

      # On main branch: actual PSR + upload to PyPI & GitHub
      - name: Release
        uses: python-semantic-release/python-semantic-release@v9.8.8
        id: release
        if: github.ref_name == 'main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

</details>

### Execution Log

<details>
<summary><code>semantic-release -vv version</code></summary>

```log
[08:25:27] INFO     [semantic_release.cli.util] INFO                  util.py:79
                    util.load_raw_config_file: Loading configuration            
                    from pyproject.toml                                         
           INFO     [semantic_release.cli.config] INFO             config.py:414
                    config.select_branch_options: Using group                   
                    'main' options, as 'main' matches 'main'                    
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 1                        
                    previous tags                                               
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:282
                    algorithm.next_version: Found 1 full                        
                    releases (excluding prereleases)                            
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:324
                    algorithm.next_version: The last full                       
                    release was 0.1.0, tagged as                                
                    <git.TagReference "refs/tags/v0.1.0">                       
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:105
                    algorithm.bfs: found latest version in                      
                    branch history: '0.1.0' (9a5b6f2)                           
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:129
                    algorithm._bfs_for_latest_version_in_histor                 
                    y: the latest version in this branch's                      
                    history is 0.1.0                                            
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:358
                    algorithm.next_version: The last full                       
                    version in this branch's history was 0.1.0                  
           INFO     [semantic_release.version.algorithm] INFO   algorithm.py:433
                    algorithm.next_version: The type of the                     
                    next release release is: minor                              
0.2.0
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 1                        
                    previous tags                                               
           INFO     [semantic_release.version.algorithm] INFO    algorithm.py:58
                    algorithm.tags_and_versions: found 1                        
                    previous tags                                               
The next version is: 0.2.0! 🚀
           INFO     [semantic_release.changelog.template] INFO   template.py:100
                    template.recursive_render: Rendering                        
                    templates from /github/workspace/templates                  
                    to /github/workspace                                        
Traceback (most recent call last):
  File "/psr/.venv/bin/semantic-release", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/commands/version.py", line 603, in version
    write_changelog_files(
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/changelog_writer.py", line 130, in write_changelog_files
    return apply_user_changelog_template_directory(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/cli/changelog_writer.py", line 80, in apply_user_changelog_template_directory
    return recursive_render(
           ^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/semantic_release/changelog/template.py", line 114, in recursive_render
    stream.dump(output_file, encoding="utf-8")
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1626, in dump
    real_fp.writelines(iterable)
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1621, in <genexpr>
    iterable = (x.encode(encoding, errors) for x in self)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1670, in __next__
    return self._next()  # type: ignore
           ^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1357, in generate
    yield self.environment.handle_exception()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/github/workspace/templates/CHANGELOG.md.j2", line 12, in top-level template code
    - {{ commit.descriptions[0] | capitalize }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }}))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/psr/.venv/lib/python3.12/site-packages/jinja2/sandbox.py", line 304, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'semantic_release.commit_parser.token.ParseError object' has no attribute 'descriptions'
```

</details>

### Additional context

Custom changelog template

```j2
# Changelog

{%- for version, release in context.history.released.items() %}

## {{ version.as_tag() }} ({{ release.tagged_date.strftime("%Y-%m-%d") }})

{%- for category, commits in release["elements"].items() %}
{# Category title: Breaking, Fix, Documentation #}
### {{ category | capitalize }}
{# List actual changes in the category #}
{%- for commit in commits %}
- {{ commit.descriptions[0] | capitalize }} ([`{{ commit.short_hash }}`]({{ commit.hexsha | commit_hash_url }}))
{%- endfor %}{# for commit #}

{%- endfor %}{# for category, commits #}

{%- endfor %}{# for version, release #}
```

**Comment by codejedi365** [comment]
@niccokunzmann, I have reviewed your repository and your issue.  Ends up this isn't related to the update, its because of your custom changelog template and your growing/different git history.

Your custom changelog template does not account for ParseError objects which represent commits of type `unknown` that do not match the designated commit syntax (in your case, angular). Your changelog template tries to extract the first line of the description on a commit that had failed to parse, which doesn't exist because previously the description was unable to be determined.  Although it is a bit counter-intuitive for PSR to pass ParseError objects on to the Changelog, this was a legacy decision before my time. 

My recommendation to your changelog template is to add a filter to skip unknown commit types:

```j2
{%- for commit in commits if category != "unknown" %}
```

The ParseError objects are from the merge commits in your git history which do not match angular commit style.  This statement is not to imply that your merge commits should match--it is only a statement of fact.  If you are going to save merge commits in your git history than I do recommend they stay as you have them `Merge pull request ...`, but you should add the following to your semantic-release configuration:

```diff
diff a/pyproject.toml b/pyproject.toml

  [tool.semantic_release.changelog]
  exclude_commit_patterns = [
      "chore*",
      "ci*",
+     '''Merge pull request .*''',
  ]
```

P.S. please make sure to fill out the bug report template more completely as it helps me answer your issues more quickly and saves me time.

**Comment by niccokunzmann** [comment]
Thank you so much! I am very new to this and we just copied the Python Project template on GitHub.... So, I hope this issue will be solved to the next people who do the same :) I will check and report back! Thank you!

**Comment by codejedi365** [comment]
You're welcome! and which python project template is that?

**Comment by niccokunzmann** [comment]
This package was created with [Copier](https://copier.readthedocs.io/) and the [browniebroke/pypackage-template](https://github.com/browniebroke/pypackage-template) project template.

So, I assume, I should implement your fix and see if it does it and then open an issue for them....

**Comment by codejedi365** [comment]
@niccokunzmann, yes, that would definitely be a good idea.  I didn't know that template was out there and since it does use python-semantic-release, it may be something I help critique in the future. If you mention me in the issue or PR, ill add on.

**Comment by browniebroke** [comment]
Thanks for reporting this and thanks for the suggested fixes @codejedi365 - I've implemented them in my template

**Comment by niccokunzmann** [comment]
cool. I will close this now as I believe that this has been fixed for me and in the template. Thanks everyone!
